services:
  kw:
    build:
      context: .
    container_name: kw
    depends_on:
      - kwdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kwdatabase:5432/kw
    ports:
      - "8082:8082"
    volumes:
      - /var/www/upload:/var/www/upload
    networks:
      - mynetwork

  kwdatabase:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    container_name: kwdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 🔥 Kalıcı veri deposu ekledik
    networks:
      - mynetwork


volumes:
  postgres_data:  # 🔥 Postgres için kalıcı veri deposu
  upload-data:


networks:
  mynetwork:
    driver: bridge
